name: MESMER-OpenSCM Runner CI-CD
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  linting-and-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
          hashFiles('environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: mesmer-openscmrunner-tests
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Mamba info
      run: mamba info
    - name: Install dev dependencies
      run: |
        which python
        make -B conda-environment
    - name: Run format and linting tests
      run: |
          isort --check --quiet src tests setup.py
          black --check src tests setup.py --exclude _version.py
          flake8 src tests setup.py
    - name: Build docs
      run: |
          sphinx-build -M html docs/source docs/build -qW

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
          hashFiles('environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: mesmer-openscmrunner-tests
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Mamba info
      run: mamba info
    - name: Install environment
      run: |
          which python
          make -B conda-environment
    - name: Run tests
      run: |
          which python
          make test_cov_xml
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          file: ./coverage.xml
          env_vars: RUNNER_OS,PYTHON_VERSION
          fail_ci_if_error: false
