name: MESMER-OpenSCM Runner CI-CD
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  linting-and-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
          hashFiles('environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        channels: conda-forge
        channel-priority: strict
        activate-environment: mesmer-openscmrunner-tests
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install dev dependencies
      run: |
        which python
        conda install mesmer pip wheel
        pip install .[dev]
    - name: Run format and linting tests
      shell: bash -l {0}
      # TODO: use make -B conda-environment when mesmer is available
      run: |
          black --exclude _version.py --check src tests setup.py
          flake8 src tests setup.py
          isort --check-only --quiet src tests setup.py
    - name: Build docs
      run: |
          sphinx-build -M html docs/source docs/build -qW

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
          hashFiles('environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        channels: conda-forge
        channel-priority: strict
        activate-environment: mesmer-openscmrunner-tests
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install test dependencies
      run: |
        which python
        conda install mesmer pip wheel
        pip install .[tests,notebooks]
    - name: Test with pytest
      env:
        MIN_COVERAGE: 90
      run: |
          pytest tests -r a --cov=mesmer-openscmrunner --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 1
          fi
